apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
spec:
  capacity:
    storage: 20Gi  
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  # Ensure this path is appropriate for your environment