apiVersion: v1
kind: Service
metadata:
  name: godbtest-service
spec:
  type: LoadBalancer  # Exposes the service externally
  ports:
    - port: 80  # Port exposed outside
      targetPort: 8080  # Port inside the container
  selector:
    app: godbtest  # Matches the label of the pods